### ISSUE TITLE
Increased GPU usage when minimizing game?

### ISSUE THREAD

**Issue by Maxunit** [NightmareXIV/Mini#1]
Sorry Eternita-S for the next "bug report" >_>

I am going through a lot of plugins, testing around and whatnot and just tried out "Mini" and observed my Hardware Temperatures and usage with HWMonitor.

I noticed, that my GPU (a GeForce GTX 1070) is currently at 75% GPU usage when the game is maximized in Borderless Windowed mode (Dual Monitor Setup) and as soon as I minimize it with Mini, the GPU usage instantly spikes to 99 - 100%.

Is this normal?

**Comment by Limiana** [comment]
Can you check if your gpu frequency differs between game being open and minimized? I'd recommend gpu-z: https://www.techpowerup.com/download/techpowerup-gpu-z/
Most programs report gpu usage frequency relative. While game is minimized, rendering gpu load should decrease and your gpu may drop some frequency to save power and cool itself down while not experiencing heavier loads:
![image_459](https://user-images.githubusercontent.com/5073202/137603420-c16ec75e-4274-40ab-ac49-73e051efc4ad.png)
But I'm afraid even if somehow game in minimized state consumes more gpu processing power than in normal state, there's not much I can do from plugin as it just calls same windows function as normal minimize button that would be available would you run game in windowed mode.
I'd also suggest enabling "Limit frame rate when client is inactive" option in display settings in game, that should limit fps of minimized game to about 15, and if that doesn't works still and if you are using msi afterburner with rtss, I can give you instructions how to make rtss slow down the game while it's inactive

**Comment by Maxunit** [comment]
Aaah okay.

I just downloaded GPU-Z and compared.

Maximized:
GPU Clock: 1860 Mhz
GPU Load: ~25%

Minimized:
GPU Clock: 1518.5 Mhz
GPU Load: 20 - 25%

Seems like HWMonitor/HWInfo reads it wrong. Then this topic can be closed. It was no issue with Mini, but with HWInfo/HWMonitor outputting wrong numbers.
