### ISSUE TITLE
MOving other  addons

### ISSUE THREAD

**Issue by DiggityMan420** [NightmareXIV/Mini#2]
I noticed when minimizing to the tray other addons get moved  specifically all the way to the topmost left side when u restore the game. Example I have is with PingPlugin see Pics [BEFORE ](https://imgshare.io/image/rSGZry)and [AFTER](https://imgshare.io/image/rSGEy6)

**Comment by Limiana** [comment]
I somehow missed this issue 👀 
Do you still have the problem?
