### ISSUE TITLE
System Tray Icon entries being duplicated in Windows 11

### ISSUE THREAD

**Issue by spicyBeefu** [NightmareXIV/Mini#5]
I assume this is due to the name # in the icon (e.g _[Mini] Final Fantasy XIV #4016_) being different every time you launch the game. 
You can view this under:
> Win11 Settings > Personalization > Taskbar > Other system tray icons

FFXIV as a system tray icon keeps being duplicated. These do not go away over time and it prevents you keeping the FFXIV icon visible without viewing hidden system tray icons.

![image](https://github.com/NightmareXIV/Mini/assets/25026032/c3c3173f-4a28-479b-97d7-81a887293468)

**Comment by rmrocks01** [comment]
It would be nice to have an option to disable the pid in tray icon as you can't properly pin it to the taskbar in windows 10 either as the name change causes it to not persist.

**Comment by Limiana** [comment]
Hello! Sorry for taking long to answer. 
I will add that option. Though, I myself use win 11 and don't have the issue somehow

**Comment by Limiana** [comment]
Should be fixed a while ago now
