### ISSUE TITLE
Will it be updated for DT?

### ISSUE THREAD

**Issue by Kichiro84** [NightmareXIV/Mini#7]
I am really sorry for using the Issue funtion.
Just wanna ask if we can look forward for an Update.

**Comment by Limiana** [comment]
Hello! Plugin already was updated but awaiting approval from main repo: https://github.com/goatcorp/DalamudPluginsD17/pull/3777
In meantime, you could download and install it manually from here: https://github.com/NightmareXIV/Mini/releases/tag/2.1.0.1

**Comment by Kichiro84** [comment]
Thank you really much! i really appreciate it!!!
