### ISSUE TITLE
DT Update question

### ISSUE THREAD

**Issue by jibby21** [NightmareXIV/Mini#8]
Heya, simple yet amazing plugin. I see it says its updated for DT but it doesnt show in the acutal plugin manager for the launcher in game as updated.

Do I manually download it form here and if so where do I put the files?

Since I see it shows as having a DT update.

Thanks!

**Comment by Limiana** [comment]
Hey!
The plugin is waiting for a merge by XIVLauncher maintainers: https://github.com/goatcorp/DalamudPluginsD17/pull/3777
If you would like to use it now, you just need to download and unpack it anywhere and in `/xlsettings` - experimental put a path to Mini.dll to "dev plugin locations". Like you add a 3rd party repo, but upper list

**Comment by jibby21** [comment]
Alrighty thanks :) hope they can get around to it soon. Have a nice day.

**Comment by shinji257** [comment]
Looks like the build got blocked in the main repo until it is fixed.
https://github.com/goatcorp/DalamudPluginsD17/pull/3777#issuecomment-2218390868

**Comment by ClareBearington** [comment]
Where do i find the Mini.dll to sideload

**Comment by Limiana** [comment]
> Where do i find the Mini.dll to sideload

https://github.com/NightmareXIV/Mini/releases Here in Releases

**Comment by AirDur** [comment]
Hello. Any update ?

**Comment by Limiana** [comment]
> Hello. Any update ?

Not yet at this moment, you can still use manual download. Build system still doesn't seems to be able to handle building the plugin. I'll probably make a workaround, though, will see.

**Comment by DevsAdvocate1** [comment]
Is there any word on getting this updated or perhaps finding it somewhere else?

![image](https://github.com/user-attachments/assets/e2b26cfd-bf2f-4603-ae72-fa48cc5e6d95)

**Comment by Limiana** [comment]
> Is there any word on getting this updated or perhaps finding it somewhere else?
> 
> ![image](https://github.com/user-attachments/assets/e2b26cfd-bf2f-4603-ae72-fa48cc5e6d95)
> 
> 

Hello, the plugin is updated, try to reinstall it (delete and install again)
